import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import type { Metadata } from "next";
import "./globals.css";
import {Roboto} from "next/font/google";
import { StoreDataProvider } from "./context/storeData";
import axios from "axios";
import React from "react";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Snakbar} from "@/components/ui/sonner";
import Loading from "./loading";



export const metadata: Metadata = {
  title: {
    template: "%s  |  Batriq",
    default: "Batriq"
  },
  description: "Generated by create next app"
};
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400",  "900"]
})
  axios.defaults.baseURL = "http://localhost:3000";
  axios.defaults.headers.options={
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,PATCH,OPTIONS",
    // 'Authorization': `Bearer ${token}`,

  }

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang="en">
      <body
        id="body"
        className={`${roboto.className} antialiased ${
          locale === "ar" && "rtl"
        }`}
      >
        <NextIntlClientProvider messages={messages}>
          <StoreDataProvider>
            <React.Suspense fallback={<Loading/>}>
            <main className=" ">{children}</main>

            </React.Suspense>
          </StoreDataProvider>
        </NextIntlClientProvider>
        <Toaster />
        <Snakbar />
      </body>
    </html>
  );
}
